const OperatingExpensesActionTypes = {
  ADD_OPEEXP_START: 'ADD_OPEEXP_START',
  ADD_OPEEXP_SUCCESS: 'ADD_OPEEXP_SUCCESS',
  ADD_OPEEXP_FAILURE: 'ADD_OPEEXP_FAILURE',

  REMOVE_OPEEXP_START: 'REMOVE_OPEEXP_START',
  REMOVE_OPEEXP_SUCCESS: 'REMOVE_OPEEXP_SUCCESS',
  REMOVE_OPEEXP_FAILURE: 'REMOVE_OPEEXP_START',

  FETCH_OPEEXPS_START: 'FETCH_OPEEXPS_START',
  FETCH_OPEEXPS_SUCCESS: 'FETCH_OPEEXPS_SUCCESS',
  FETCH_OPEEXPS_FAILURE: 'FETCH_OPEEXPS_FAILURE',

  ADD_EXPTYPE_START: 'ADD_EXPTYPE_START',
  ADD_EXPTYPE_SUCCESS: 'ADD_EXPTYPE_SUCCESS',
  ADD_EXPTYPE_FAILURE: 'ADD_EXPTYPE_FAILURE',

  REMOVE_EXPTYPE_START: 'REMOVE_EXPTYPE_START',
  REMOVE_EXPTYPE_SUCCESS: 'REMOVE_EXPTYPE_SUCCESS',
  REMOVE_EXPTYPE_FAILURE: 'REMOVE_EXPTYPE_START',

  FETCH_EXPTYPES_START: 'FETCH_EXPTYPES_START',
  FETCH_EXPTYPES_SUCCESS: 'FETCH_EXPTYPES_SUCCESS',
  FETCH_EXPTYPES_FAILURE: 'FETCH_EXPTYPES_FAILURE',

  ADD_MATEXP_START: 'ADD_MATEXP_START',
  ADD_MATEXP_SUCCESS: 'ADD_MATEXP_SUCCESS',
  ADD_MATEXP_FAILURE: 'ADD_MATEXP_FAILURE',

  REMOVE_MATEXP_START: 'REMOVE_MATEXP_START',
  REMOVE_MATEXP_SUCCESS: 'REMOVE_MATEXP_SUCCESS',
  REMOVE_MATEXP_FAILURE: 'REMOVE_MATEXP_START',

  FETCH_MATEXPS_START: 'FETCH_MATEXPS_START',
  FETCH_MATEXPS_SUCCESS: 'FETCH_MATEXPS_SUCCESS',
  FETCH_MATEXPS_FAILURE: 'FETCH_MATEXPS_FAILURE',
};

export default OperatingExpensesActionTypes;
