const ProjectAndClientActionTypes = {
  ADD_CLIENT_START: 'ADD_CLIENT_START',
  ADD_CLIENT_SUCCESS: 'ADD_CLIENT_SUCCESS',
  ADD_CLIENT_FAILURE: 'ADD_CLIENT_FAILURE',

  ADD_PROJECT_START: 'ADD_PROJECT_START',
  ADD_PROJECT_SUCCESS: 'ADD_PROJECT_SUCCESS',
  ADD_PROJECT_FAILURE: 'ADD_PROJECT_FAILURE',

  REMOVE_CLIENT_START: 'REMOVE_CLIENT_START',
  REMOVE_CLIENT_SUCCESS: 'REMOVE_CLIENT_SUCCESS',
  REMOVE_CLIENT_FAILURE: 'REMOVE_CLIENT_START',

  REMOVE_PROJECT_START: 'REMOVE_PROJECT_START',
  REMOVE_PROJECT_SUCCESS: 'REMOVE_PROJECT_SUCCESS',
  REMOVE_PROJECT_FAILURE: 'REMOVE_PROJECT_START',

  FETCH_CLIENTS_START: 'FETCH_CLIENTS_START',
  FETCH_CLIENTS_SUCCESS: 'FETCH_CLIENTS_SUCCESS',
  FETCH_CLIENTS_FAILURE: 'FETCH_CLIENTS_FAILURE',

  FETCH_PROJECTS_START: 'FETCH_PROJECTS_START',
  FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_FAILURE: 'FETCH_PROJECTS_FAILURE',

  UPDATE_PROJECT_START: 'UPDATE_PROJECT_START',
  UPDATE_PROJECT_SUCCESS: 'UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_FAILURE: 'UPDATE_PROJECT_FAILURE',
};

export default ProjectAndClientActionTypes;
