const TimeEntryActionTypes = {
  ADD_TIME_ENTRY_START: 'ADD_TIME_ENTRY_START',
  ADD_TIME_ENTRY_SUCCESS: 'ADD_TIME_ENTRY_SUCCESS',
  ADD_TIME_ENTRY_FAILURE: 'ADD_TIME_ENTRY_FAILURE',

  REMOVE_TIME_ENTRY_START: 'REMOVE_TIME_ENTRY_START',
  REMOVE_TIME_ENTRY_SUCCESS: 'REMOVE_TIME_ENTRY_SUCCESS',
  REMOVE_TIME_ENTRY_FAILURE: 'REMOVE_TIME_ENTRY_FAILURE',

  FETCH_TIME_ENTRIES_START: 'FETCH_TIME_ENTRIES_START',
  FETCH_TIME_ENTRIES_SUCCESS: 'FETCH_TIME_ENTRIES_SUCCESS',
  FETCH_TIME_ENTRIES_FAILURE: 'FETCH_TIME_ENTRIES_FAILURE',

  FETCH_CA_TIME_ENTRIES_START: 'FETCH_CA_TIME_ENTRIES_START',
  FETCH_CA_TIME_ENTRIES_SUCCESS: 'FETCH_CA_TIME_ENTRIES_SUCCESS',
  FETCH_CA_TIME_ENTRIES_FAILURE: 'FETCH_CA_TIME_ENTRIES_FAILURE',

  ADD_CA_TIME_ENTRY_SUCCESS: 'ADD_CA_TIME_ENTRY_SUCCESS',
};

export default TimeEntryActionTypes;
