const CategoryActionTypes = {
  ADD_CATEGORY_START: 'ADD_CATEGORY_START',
  ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
  ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE',

  REMOVE_CATEGORY_START: 'REMOVE_CATEGORY_START',
  REMOVE_CATEGORY_SUCCESS: 'REMOVE_CATEGORY_SUCCESS',
  REMOVE_CATEGORY_FAILURE: 'REMOVE_CATEGORY_START',

  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',
};

export default CategoryActionTypes;
