const WorkspaceActionTypes = {
  CHANGE_SELECTED_WORKSPACE: 'CHANGE_SELECTED_WORKSPACE',

  ADD_WORKSPACE_START: 'ADD_WORKSPACE_START',
  ADD_WORKSPACE_SUCCESS: 'ADD_WORKSPACE_SUCCESS',
  ADD_WORKSPACE_FAILURE: 'ADD_WORKSPACE_FAILURE',

  REMOVE_WORKSPACE_START: 'REMOVE_WORKSPACE_START',
  REMOVE_WORKSPACE_SUCCESS: 'REMOVE_WORKSPACE_SUCCESS',
  REMOVE_WORKSPACE_FAILURE: 'REMOVE_WORKSPACE_FAILURE',

  ADD_MEMBER_START: 'ADD_MEMBER_START',
  ADD_MEMBER_SUCCESS: 'ADD_MEMBER_SUCCESS',
  ADD_MEMBER_FAILURE: 'ADD_MEMBER_FAILURE',

  REMOVE_MEMBER_START: 'REMOVE_MEMBER_START',
  REMOVE_MEMBER_SUCCESS: 'REMOVE_MEMBER_SUCCESS',
  REMOVE_MEMBER_FAILURE: 'REMOVE_MEMBER_FAILURE',

  ACCEPT_INVITATION_START: 'ACCEPT_INVITATION_START',
  ACCEPT_INVITATION_SUCCESS: 'ACCEPT_INVITATION_SUCCESS',
  ACCEPT_INVITATION_FAILURE: 'ACCEPT_INVITATION_FAILURE',

  DECLINE_INVITATION_START: 'DECLINE_INVITATION_START',
  DECLINE_INVITATION_SUCCESS: 'DECLINE_INVITATION_SUCCESS',
  DECLINE_INVITATION_FAILURE: 'DECLINE_INVITATION_FAILURE',

  UPDATE_SELECTED_WORKSPACE_DATA_START:
    'UPDATE_SELECTED_WORKSPACE_DATA_START',
  UPDATE_SELECTED_WORKSPACE_DATA_SUCCESS:
    'UPDATE_SELECTED_WORKSPACE_DATA_SUCCESS',
  UPDATE_SELECTED_WORKSPACE_DATA_FAILURE:
    'UPDATE_SELECTED_WORKSPACE_DATA_FAILURE',

  ADD_WORKSPACES_LIST: 'ADD_WORKSPACES_LIST',

  UPDATE_LOGO_START: 'UPDATE_LOGO_START',
  UPDATE_LOGO_SUCCESS: 'UPDATE_LOGO_SUCCESS',
  UPDATE_LOGO_FAILURE: 'UPDATE_LOGO_FAILURE',

  CHANGE_MEMBER_ROLE_START: 'CHANGE_MEMBER_ROLE_START',
  CHANGE_MEMBER_ROLE_SUCCESS: 'CHANGE_MEMBER_ROLE_SUCCESS',
  CHANGE_MEMBER_ROLE_FAILURE: 'CHANGE_MEMBER_ROLE_FAILURE',

  UPDATE_WORKSPACE_SETTINGS_START: 'UPDATE_WORKSPACE_SETTINGS_START',
  UPDATE_WORKSPACE_SETTINGS_SUCCESS:
    'UPDATE_WORKSPACE_SETTINGS_SUCCESS',
  UPDATE_WORKSPACE_SETTINGS_FAILURE:
    'UPDATE_WORKSPACE_SETTINGS_FAILURE',

  NEW: 'NEW',
};

export default WorkspaceActionTypes;
